package arena

const Vitalset_updated___json_string = `{
	"spec":{
		"respiratory_rate":5,
		"spo2":33,
		"blood_pressure":{
		   "systolic":108,
		   "diastolic":99
		},
		"etco2":12,
		"temperature_blood":14.523456,
		"temperature_peripheral":14.430864,
		"ecg":{
		   "heart_rate":30,
		   "basic_rhythm":"sinus",
		   "extrasystole":{
			  "type":"none",
			  "probability":4
		   },
		   "severity":2,
		   "allow_pacing":false,
		   "emd_pea":false
		},
		"eyes":{
		   "left":{
			  "eyelid_position":"open",
			  "pupil_size":4,
			  "pupil_responsiveness":"normal"
		   },
		   "right":{
			  "eyelid_position":"open",
			  "pupil_size":4,
			  "pupil_responsiveness":"normal"
		   },
		   "blink_rate":"normal"
		},
		"airway_obstruction":{
		   "tongue_edema":"normal"
		},
		"lung_sounds":{
		   "left":{
			  "anterior_upper":"normal",
			  "anterior_upper_volume":50,
			  "anterior_lower":"normal",
			  "anterior_lower_volume":50,
			  "posterior_upper":"normal",
			  "posterior_upper_volume":50,
			  "posterior_lower":"normal",
			  "posterior_lower_volume":50
		   },
		   "right":{
			  "anterior_upper":"normal",
			  "anterior_upper_volume":50,
			  "anterior_lower":"normal",
			  "anterior_lower_volume":50,
			  "anterior_middle":"normal",
			  "anterior_middle_volume":50,
			  "posterior_upper":"normal",
			  "posterior_upper_volume":50,
			  "posterior_lower":"normal",
			  "posterior_lower_volume":50
		   }
		},
		"heart_sounds":{
		   "aortic":"normal",
		   "aortic_volume":50,
		   "pulmonary":"normal",
		   "pulmonary_volume":50,
		   "tricuspid":"normal",
		   "tricuspid_volume":50,
		   "mitral":"normal",
		   "mitral_volume":50
		},
		"bowel_sounds":{
		   "bowel":"normal_20_years_old",
		   "bowel_volume":50
		},
		"pulses":{
		   "central":"normal",
		   "central_limited":"normal",
		   "right_leg":"normal",
		   "right_leg_limited":"normal",
		   "left_leg":"normal",
		   "left_leg_limited":"normal",
		   "right_foot":"normal",
		   "right_foot_limited":"normal",
		   "left_foot":"normal",
		   "left_foot_limited":"normal",
		   "right_arm":"normal",
		   "right_arm_limited":"normal",
		   "left_arm":"normal",
		   "left_arm_limited":"normal",
		   "right_hand":"normal",
		   "right_hand_limited":"normal",
		   "left_hand":"normal",
		   "left_hand_limited":"normal"
		}
	 }
 }`
