package arena

const Vitalset_patched___json_string = `{
	   "spec":{
		  "respiratory_rate":4,
		  "spo2":4,
		  "blood_pressure":{
			 "systolic":100,
			 "diastolic":100
		  },
		  "etco2":4,
		  "temperature_blood":4.4,
		  "temperature_peripheral":4.4,
		  "ecg":{
			 "heart_rate":4,
			 "basic_rhythm":"sinus",
			 "extrasystole":{
				"type":"none",
				"probability":4
			 },
			 "severity":2,
			 "allow_pacing":false,
			 "emd_pea":false
		  },
		  "eyes":{
			 "left":{
				"eyelid_position":"open",
				"pupil_size":4,
				"pupil_responsiveness":"normal"
			 },
			 "right":{
				"eyelid_position":"open",
				"pupil_size":4,
				"pupil_responsiveness":"normal"
			 },
			 "blink_rate":"normal"
		  },
		  "airway_obstruction":{
			 "tongue_edema":"normal"
		  },
		  "lung_sounds":{
			 "left":{
				"anterior_upper":"normal",
				"anterior_upper_volume":50,
				"anterior_lower":"normal",
				"anterior_lower_volume":50,
				"posterior_upper":"normal",
				"posterior_upper_volume":50,
				"posterior_lower":"normal",
				"posterior_lower_volume":50
			 },
			 "right":{
				"anterior_upper":"normal",
				"anterior_upper_volume":50,
				"anterior_lower":"normal",
				"anterior_lower_volume":50,
				"anterior_middle":"normal",
				"anterior_middle_volume":50,
				"posterior_upper":"normal",
				"posterior_upper_volume":50,
				"posterior_lower":"normal",
				"posterior_lower_volume":50
			 }
		  },
		  "heart_sounds":{
			 "aortic":"normal",
			 "aortic_volume":50,
			 "pulmonary":"normal",
			 "pulmonary_volume":50,
			 "tricuspid":"normal",
			 "tricuspid_volume":50,
			 "mitral":"normal",
			 "mitral_volume":50
		  },
		  "bowel_sounds":{
			 "bowel":"normal_20_years_old",
			 "bowel_volume":50
		  }
	   }
 }`
