// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: pbfooitem.proto

package arena

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBFooItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Email     string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Roles     []string               `protobuf:"bytes,3,rep,name=Roles,proto3" json:"Roles,omitempty"`
	APIKey    string                 `protobuf:"bytes,4,opt,name=APIKey,proto3" json:"APIKey,omitempty"`
	Profile   *PBFooProfile          `protobuf:"bytes,5,opt,name=Profile,proto3" json:"Profile,omitempty"`
	Username  string                 `protobuf:"bytes,6,opt,name=Username,proto3" json:"Username,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *PBFooItem) Reset() {
	*x = PBFooItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbfooitem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBFooItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBFooItem) ProtoMessage() {}

func (x *PBFooItem) ProtoReflect() protoreflect.Message {
	mi := &file_pbfooitem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBFooItem.ProtoReflect.Descriptor instead.
func (*PBFooItem) Descriptor() ([]byte, []int) {
	return file_pbfooitem_proto_rawDescGZIP(), []int{0}
}

func (x *PBFooItem) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *PBFooItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PBFooItem) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *PBFooItem) GetAPIKey() string {
	if x != nil {
		return x.APIKey
	}
	return ""
}

func (x *PBFooItem) GetProfile() *PBFooProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *PBFooItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PBFooItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PBFooItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PBFooProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dob      string         `protobuf:"bytes,1,opt,name=Dob,proto3" json:"Dob,omitempty"`
	Name     string         `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	About    string         `protobuf:"bytes,3,opt,name=About,proto3" json:"About,omitempty"`
	Address  string         `protobuf:"bytes,4,opt,name=Address,proto3" json:"Address,omitempty"`
	Company  string         `protobuf:"bytes,5,opt,name=Company,proto3" json:"Company,omitempty"`
	Location *PBFooLocation `protobuf:"bytes,6,opt,name=Location,proto3" json:"Location,omitempty"`
}

func (x *PBFooProfile) Reset() {
	*x = PBFooProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbfooitem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBFooProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBFooProfile) ProtoMessage() {}

func (x *PBFooProfile) ProtoReflect() protoreflect.Message {
	mi := &file_pbfooitem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBFooProfile.ProtoReflect.Descriptor instead.
func (*PBFooProfile) Descriptor() ([]byte, []int) {
	return file_pbfooitem_proto_rawDescGZIP(), []int{1}
}

func (x *PBFooProfile) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *PBFooProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PBFooProfile) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *PBFooProfile) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PBFooProfile) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *PBFooProfile) GetLocation() *PBFooLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

type PBFooLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat  float64 `protobuf:"fixed64,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Long float64 `protobuf:"fixed64,2,opt,name=Long,proto3" json:"Long,omitempty"`
}

func (x *PBFooLocation) Reset() {
	*x = PBFooLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbfooitem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBFooLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBFooLocation) ProtoMessage() {}

func (x *PBFooLocation) ProtoReflect() protoreflect.Message {
	mi := &file_pbfooitem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBFooLocation.ProtoReflect.Descriptor instead.
func (*PBFooLocation) Descriptor() ([]byte, []int) {
	return file_pbfooitem_proto_rawDescGZIP(), []int{2}
}

func (x *PBFooLocation) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *PBFooLocation) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

var File_pbfooitem_proto protoreflect.FileDescriptor

var file_pbfooitem_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x66, 0x6f, 0x6f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x66, 0x6f, 0x6f, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x02, 0x0a,
	0x09, 0x50, 0x42, 0x46, 0x6f, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x12, 0x30,
	0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x50, 0x42, 0x46, 0x6f, 0x6f,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0xb3, 0x01, 0x0a, 0x0c, 0x50, 0x42, 0x46, 0x6f, 0x6f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x44, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x62, 0x6f, 0x75, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x62, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x12, 0x33, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x50,
	0x42, 0x46, 0x6f, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x0d, 0x50, 0x42, 0x46, 0x6f, 0x6f, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x4c, 0x6f, 0x6e, 0x67, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x3b, 0x61, 0x72, 0x65, 0x6e, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbfooitem_proto_rawDescOnce sync.Once
	file_pbfooitem_proto_rawDescData = file_pbfooitem_proto_rawDesc
)

func file_pbfooitem_proto_rawDescGZIP() []byte {
	file_pbfooitem_proto_rawDescOnce.Do(func() {
		file_pbfooitem_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbfooitem_proto_rawDescData)
	})
	return file_pbfooitem_proto_rawDescData
}

var file_pbfooitem_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pbfooitem_proto_goTypes = []interface{}{
	(*PBFooItem)(nil),             // 0: foo.item.PBFooItem
	(*PBFooProfile)(nil),          // 1: foo.item.PBFooProfile
	(*PBFooLocation)(nil),         // 2: foo.item.PBFooLocation
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_pbfooitem_proto_depIdxs = []int32{
	1, // 0: foo.item.PBFooItem.Profile:type_name -> foo.item.PBFooProfile
	3, // 1: foo.item.PBFooItem.CreatedAt:type_name -> google.protobuf.Timestamp
	3, // 2: foo.item.PBFooItem.UpdatedAt:type_name -> google.protobuf.Timestamp
	2, // 3: foo.item.PBFooProfile.Location:type_name -> foo.item.PBFooLocation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pbfooitem_proto_init() }
func file_pbfooitem_proto_init() {
	if File_pbfooitem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbfooitem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBFooItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbfooitem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBFooProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbfooitem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBFooLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbfooitem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbfooitem_proto_goTypes,
		DependencyIndexes: file_pbfooitem_proto_depIdxs,
		MessageInfos:      file_pbfooitem_proto_msgTypes,
	}.Build()
	File_pbfooitem_proto = out.File
	file_pbfooitem_proto_rawDesc = nil
	file_pbfooitem_proto_goTypes = nil
	file_pbfooitem_proto_depIdxs = nil
}
