// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: pbsimeventregistereventcmd.proto

package arena

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBSimEventRegisterEventCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion    string                 `protobuf:"bytes,1,opt,name=ApiVersion,proto3" json:"ApiVersion,omitempty"`
	SimulatorName string                 `protobuf:"bytes,2,opt,name=SimulatorName,proto3" json:"SimulatorName,omitempty"`
	Tenant        string                 `protobuf:"bytes,3,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	EventID       string                 `protobuf:"bytes,4,opt,name=EventID,proto3" json:"EventID,omitempty"`
	TimeStamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	// Types that are assignable to Arguments:
	//	*PBSimEventRegisterEventCmd_PacingArguments
	Arguments isPBSimEventRegisterEventCmd_Arguments `protobuf_oneof:"Arguments"`
}

func (x *PBSimEventRegisterEventCmd) Reset() {
	*x = PBSimEventRegisterEventCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbsimeventregistereventcmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBSimEventRegisterEventCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBSimEventRegisterEventCmd) ProtoMessage() {}

func (x *PBSimEventRegisterEventCmd) ProtoReflect() protoreflect.Message {
	mi := &file_pbsimeventregistereventcmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBSimEventRegisterEventCmd.ProtoReflect.Descriptor instead.
func (*PBSimEventRegisterEventCmd) Descriptor() ([]byte, []int) {
	return file_pbsimeventregistereventcmd_proto_rawDescGZIP(), []int{0}
}

func (x *PBSimEventRegisterEventCmd) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PBSimEventRegisterEventCmd) GetSimulatorName() string {
	if x != nil {
		return x.SimulatorName
	}
	return ""
}

func (x *PBSimEventRegisterEventCmd) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *PBSimEventRegisterEventCmd) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *PBSimEventRegisterEventCmd) GetTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (m *PBSimEventRegisterEventCmd) GetArguments() isPBSimEventRegisterEventCmd_Arguments {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (x *PBSimEventRegisterEventCmd) GetPacingArguments() *PBPacingArguments {
	if x, ok := x.GetArguments().(*PBSimEventRegisterEventCmd_PacingArguments); ok {
		return x.PacingArguments
	}
	return nil
}

type isPBSimEventRegisterEventCmd_Arguments interface {
	isPBSimEventRegisterEventCmd_Arguments()
}

type PBSimEventRegisterEventCmd_PacingArguments struct {
	PacingArguments *PBPacingArguments `protobuf:"bytes,10,opt,name=PacingArguments,proto3,oneof"`
}

func (*PBSimEventRegisterEventCmd_PacingArguments) isPBSimEventRegisterEventCmd_Arguments() {}

type PBPacingArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	MeasuredCurrent int32                  `protobuf:"varint,2,opt,name=MeasuredCurrent,proto3" json:"MeasuredCurrent,omitempty"`
	Capture         bool                   `protobuf:"varint,3,opt,name=Capture,proto3" json:"Capture,omitempty"`
}

func (x *PBPacingArguments) Reset() {
	*x = PBPacingArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbsimeventregistereventcmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBPacingArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBPacingArguments) ProtoMessage() {}

func (x *PBPacingArguments) ProtoReflect() protoreflect.Message {
	mi := &file_pbsimeventregistereventcmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBPacingArguments.ProtoReflect.Descriptor instead.
func (*PBPacingArguments) Descriptor() ([]byte, []int) {
	return file_pbsimeventregistereventcmd_proto_rawDescGZIP(), []int{1}
}

func (x *PBPacingArguments) GetTimeStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

func (x *PBPacingArguments) GetMeasuredCurrent() int32 {
	if x != nil {
		return x.MeasuredCurrent
	}
	return 0
}

func (x *PBPacingArguments) GetCapture() bool {
	if x != nil {
		return x.Capture
	}
	return false
}

var File_pbsimeventregistereventcmd_proto protoreflect.FileDescriptor

var file_pbsimeventregistereventcmd_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x62, 0x73, 0x69, 0x6d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x66, 0x6f, 0x6f, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x02,
	0x0a, 0x1a, 0x50, 0x42, 0x53, 0x69, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x41, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x41, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d,
	0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x12, 0x38, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x47,
	0x0a, 0x0f, 0x50, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x69, 0x74,
	0x65, 0x6d, 0x2e, 0x50, 0x42, 0x50, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x48, 0x00, 0x52, 0x0f, 0x50, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x41, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x11, 0x50, 0x42, 0x50, 0x61, 0x63, 0x69, 0x6e,
	0x67, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x28, 0x0a, 0x0f, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x64,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x4d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x64, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x61, 0x72,
	0x65, 0x6e, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbsimeventregistereventcmd_proto_rawDescOnce sync.Once
	file_pbsimeventregistereventcmd_proto_rawDescData = file_pbsimeventregistereventcmd_proto_rawDesc
)

func file_pbsimeventregistereventcmd_proto_rawDescGZIP() []byte {
	file_pbsimeventregistereventcmd_proto_rawDescOnce.Do(func() {
		file_pbsimeventregistereventcmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbsimeventregistereventcmd_proto_rawDescData)
	})
	return file_pbsimeventregistereventcmd_proto_rawDescData
}

var file_pbsimeventregistereventcmd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbsimeventregistereventcmd_proto_goTypes = []interface{}{
	(*PBSimEventRegisterEventCmd)(nil), // 0: foo.item.PBSimEventRegisterEventCmd
	(*PBPacingArguments)(nil),          // 1: foo.item.PBPacingArguments
	(*timestamppb.Timestamp)(nil),      // 2: google.protobuf.Timestamp
}
var file_pbsimeventregistereventcmd_proto_depIdxs = []int32{
	2, // 0: foo.item.PBSimEventRegisterEventCmd.TimeStamp:type_name -> google.protobuf.Timestamp
	1, // 1: foo.item.PBSimEventRegisterEventCmd.PacingArguments:type_name -> foo.item.PBPacingArguments
	2, // 2: foo.item.PBPacingArguments.TimeStamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbsimeventregistereventcmd_proto_init() }
func file_pbsimeventregistereventcmd_proto_init() {
	if File_pbsimeventregistereventcmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbsimeventregistereventcmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBSimEventRegisterEventCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbsimeventregistereventcmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBPacingArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pbsimeventregistereventcmd_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PBSimEventRegisterEventCmd_PacingArguments)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbsimeventregistereventcmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbsimeventregistereventcmd_proto_goTypes,
		DependencyIndexes: file_pbsimeventregistereventcmd_proto_depIdxs,
		MessageInfos:      file_pbsimeventregistereventcmd_proto_msgTypes,
	}.Build()
	File_pbsimeventregistereventcmd_proto = out.File
	file_pbsimeventregistereventcmd_proto_rawDesc = nil
	file_pbsimeventregistereventcmd_proto_goTypes = nil
	file_pbsimeventregistereventcmd_proto_depIdxs = nil
}
